# Generated by Django 5.1 on 2024-09-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', protocol='ipv4')),
                ('port', models.IntegerField()),
                ('icon', models.FilePathField()),
            ],
        ),
    ]
