# Generated by Django 5.1 on 2024-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='https',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='use_reverse_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
